name: 'Akcja CI'
on:
  push:
    branches:
      - main
  workflow_dispatch:  
jobs:
  ci:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/chackout@v4.1.1
      - name: 'uruchom moja wlasna akcje kontenera'
        id: my-action
        uses: ./
        with:
          who-to-greet: "@wulfland"
      - name: Output the answer
        run: echo "the answer is ${{ steps.my-action.outputs.answer}}"
      - name: Test the container
        if: ${{ steps.my-action.outputs.answer != 42}}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1
