name: My First Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first_job:
    name: moje pierwsze zadanie
    runs-on: ubuntu-latest
    steps:
      - name: pozdrów użytkownika
      - run: echo "Hello world from ${{ github.actor }}"
      - shell: bash
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: tree
